int1 = int(input("Please eneter your 1st integer: "))
int2 = int(input("Please eneter your 2nd integer: "))
int3 = int(input("Please eneter your 3rd integer: "))
avgTotal= float((int1 + int2 +int3)/3)
print("The average of "+str(int1)+", "+str(int2)+" and "+str(int3)+" is "+str(avgTotal))
print("Complete!")